# ☼  ☀  ☁  ★☆☼  ☀  ☁  ★☆☼  ☀  ☁  ★☆☼  ☀  ☁  ★☆☼  ☀  ☁  ★☆☼  ☀  ☁  ★☆
 
# ☂"  等一下...  雨會停嗎. . . 

<div class="clearfix" style="padding: 10px; padding-left: 0px">
<img src="https://wallpaperscraft.com/image/dog_watching_window_rain_glass_drops_66656_3840x2400.jpg" width="650px" style="display: inline-block; margin-top: 5px;">
</div>

# ☼  ☀  ☁  ★☆☼  ☀  ☁  ★☆☼  ☀  ☁  ★☆☼  ☀  ☁  ★☆☼  ☀  ☁  ★☆☼  ☀  ☁  ★☆

## Import modules

In [1]:
import pandas as pd
import numpy as np
import scipy.stats as stats
import pylab as pl
from sklearn.cross_validation import train_test_split
from patsy import dmatrices
from sklearn import metrics
from sklearn.linear_model import LogisticRegression
from sklearn.cross_validation import cross_val_score

## Import raw data

In [2]:
# Read excel
xlsx102 = pd.ExcelFile(r'C:\Users\Olly\Desktop\Rain\102年古亭站_20140417.xls')
xlsx103 = pd.ExcelFile(r'C:\Users\Olly\Desktop\Rain\103年古亭站_20150324.xls')
xlsx104 = pd.ExcelFile(r'C:\Users\Olly\Desktop\Rain\104年古亭站_20160318.xls')

sheet1 = pd.concat([xlsx102.parse(0),xlsx103.parse(0),xlsx104.parse(0)])
print("★☆ Rows : ", sheet1.shape[0], "; Columns : ", sheet1.shape[1])
sheet1.index= range(sheet1.shape[0])
sheet1

★☆ Rows :  19700 ; Columns :  27

,日期,測站,測項,00,01,02,03,04,05,06,...,14,15,16,17,18,19,20,21,22,23
0,2013/01/01,古亭,AMB_TEMP,13,13,14,14,14,14,14,...,14,14,13,14,14,14,14,14,14,14
1,2013/01/01,古亭,CH4,1.9,1.9,1.9,1.9,1.9,1.9,1.9,...,2,2,1.9,1.9,1.9,2,1.9,2,1.9,2
2,2013/01/01,古亭,CO,0.46,0.48,0.44,0.44,0.43,0.39,0.37,...,0.59,0.64,0.59,0.52,0.65,0.57,0.6,0.57,0.56,0.56
3,2013/01/01,古亭,NMHC,0.2,0.21,0.17,0.19,0.2,0.19,0.18,...,0.29,0.3,0.27,0.24,0.3,0.27,0.26,0.27,0.26,0.24
4,2013/01/01,古亭,NO,3.8,3.5,3.4,4.2,4,3.9,3.9,...,12,17,14,9.1,17,11,11,12,10,8.1
5,2013/01/01,古亭,NO2,13,14,14,11,11,11,10,...,27,29,28,26,31,29,30,28,26,26
6,2013/01/01,古亭,NOx,17,17,17,15,15,15,14,...,39,46,41,35,47,40,40,40,37,34
7,2013/01/01,古亭,O3,8.9,9.7,9.8,10,9.7,8.8,9.4,...,3,2.5,2.8,3.6,2.2,3.1,2.8,2.8,3.5,4.1
8,2013/01/01,古亭,PM10,53,54,62,55,50,46,47,...,39,33,31,33,31,34,27,33,32,34
9,2013/01/01,古亭,PM2.5,27,27,25,27,28,32,32,...,24,31,24,24,20,23,24,28,26,17
10,2013/01/01,古亭,RAINFALL,NR,NR,NR,NR,NR,NR,NR,...,0.4,0.8,1,0.6,1,0.6,0.2,0.2,1.6,0.6
11,2013/01/01,古亭,RH,71,72,71,69,70,72,74,...,92,93,93,93,93,94,93,93,94,94
12,2013/01/01,古亭,SO2,2,2.2,2.3,2.2,2.3,2.2,2.1,...,2.6,2.6,2.5,2.7,2.7,2.5,2.4,2.6,2.4,2.4
13,2013/01/01,古亭,THC,2.1,2.1,2.1,2.1,2.1,2.1,2.1,...,2.2,2.3,2.2,2.2,2.2,2.2,2.2,2.2,2.2,2.2
14,2013/01/01,古亭,WD_HR,97,93,69,76,79,97,97,...,88,67,84,85,85,94,78,98,93,102
15,2013/01/01,古亭,WIND_DIREC,98,76,69,83,100,95,96,...,85,60,81,73,104,79,99,98,94,109
16,2013/01/01,古亭,WIND_SPEED,2.5,2.6,2.6,2,1.8,2.1,2.1,...,1.6,1.6,2.1,1.5,1.5,1.2,1.5,1.2,1.2,0.9
17,2013/01/01,古亭,WS_HR,2.3,2.6,2.6,2.1,1.9,2.1,2.2,...,1.8,1.5,1.7,1.8,1.5,1.3,1,1.3,1.4,0.9
18,2013/01/02,古亭,AMB_TEMP,15,15,15,16,15,16,15,...,20,20,19,19,18,18,18,18,18,17
19,2013/01/02,古亭,CH4,1.9,1.9,1.9,2,2,2.3,2.4,...,2,1.9,1.9,1.9,1.9,2.1,2,1.9,1.8,1.9
20,2013/01/02,古亭,CO,0.4,0.36,0.33,0.36,0.43,0.63,1.04,...,.91#,0.69,0.67,1.08,1.42,2.12,1.46,0.69,0.44,0.43
21,2013/01/02,古亭,NMHC,0.2,0.18,0.2,0.2,0.22,0.34,0.47,...,0.49,0.33,0.33,0.46,0.58,0.86,0.55,0.21,0.11,0.12
22,2013/01/02,古亭,NO,5.2,4.1,3.4,4,3.7,14,48,...,17#,8.1,5.3,18,26,57,44,11,3.1,2.5
23,2013/01/02,古亭,NO2,17,12,11,13,13,23,25,...,40#,33,29,38,44,45,40,30,20,20
24,2013/01/02,古亭,NOx,22,16,15,17,17,37,73,...,56#,41,34,57,69,102,84,41,23,23
25,2013/01/02,古亭,O3,7.6,9.6,11,9.6,7.5,2.6,1.9,...,10,16,17,7.9,2.3,1.3,1.2,13,24,24
26,2013/01/02,古亭,PM10,29,22,16,18,21,24,25,...,73,62,51,55,57,64,58,60,47,42
27,2013/01/02,古亭,PM2.5,14,7,16,10,13,8,14,...,36,37,24,30,19,24,29,27,22,14
28,2013/01/02,古亭,RAINFALL,0.2,NR,NR,NR,NR,NR,NR,...,NR,NR,NR,NR,NR,NR,0.2,NR,0.2,NR
29,2013/01/02,古亭,RH,93,92,90,89,91,91,90,...,73,73,81,84,85,86,89,88,85,84
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
19670,2015/12/30,古亭,NOx,8.9,7.4,6.3,7.4,6.1,7.3,17,...,32,29,30,29,33,26,22,21,19,14
19671,2015/12/30,古亭,O3,37,37,38,36,38,34,27,...,21,21,21,21,19,23,26,25,27,30
19672,2015/12/30,古亭,PM10,36,32,38,36,46,31,21,...,21,25,32,40,45,43,36,42,52,48
19673,2015/12/30,古亭,PM2.5,14,12,15,17,16,12,4,...,0,4,6,8,7,3,4,6,10,8
19674,2015/12/30,古亭,RAINFALL,NR,NR,NR,NR,NR,NR,NR,...,NR,NR,NR,NR,NR,NR,NR,NR,NR,NR
19675,2015/12/30,古亭,RH,91,93,92,93,92,93,92,...,93,93,93,94,94,94,93,91,90,94
19676,2015/12/30,古亭,SO2,1.6,2.5,3.1,4.2,2.7,1.5,1.4,...,4.2,2.9,2.7,1.9,2.4,1.9,2.9,2.7,3.9,2.2
19677,2015/12/30,古亭,THC,1.9,1.9,2,2,2,2,2,...,2,2,2,2.1,2.1,2.1,2,2,2,2
19678,2015/12/30,古亭,WD_HR,99,90,99,101,105,103,86,...,73,79,86,94,96,98,94,99,99,102
19679,2015/12/30,古亭,WIND_DIREC,101,95,86,103,109,103,101,...,86,85,89,88,97,106,90,101,91,102
19680,2015/12/30,古亭,WIND_SPEED,3,2.2,2.2,2.7,2.7,2.6,2,...,3.3,3.3,2.7,2.6,3.2,2.5,2.3,2.2,1.5,2.2
19681,2015/12/30,古亭,WS_HR,2.8,2.5,2.6,2.3,2.4,2.1,2,...,2.9,2.6,2.5,2.4,2.5,2.2,2.3,2,1.9,2.2
19682,2015/12/31,古亭,AMB_TEMP,15,15,15,15,15,15,15,...,17,16,17,17,17,17,17,17,17,17
19683,2015/12/31,古亭,CH4,1.9,1.9,1.9,1.8,1.9,1.9,1.8,...,2,2,2,2,2,2,1.9,1.9,2,2
19684,2015/12/31,古亭,CO,0.25,0.2,0.2,0.18,0.17,0.19,0.24,...,0.68,0.69,0.65,0.79,0.94,0.81,0.66,0.57,0.58,0.51
19685,2015/12/31,古亭,NMHC,0.08,0.07,0.03,0.03,0.03,0.04,0.05,...,0.18,0.18,0.18,0.21,0.21,0.17,0.13,0.11,0.11,0.09
19686,2015/12/31,古亭,NO,0.9,0.8,0.6,1.1,1.3,1.3,2.2,...,4.6,4.2,4.2,4.6,4.7,3.1,2.6,2.1,2.1,1.8
19687,2015/12/31,古亭,NO2,7.1,5.1,4.9,4.5,4.8,6.9,12,...,26,26,30,34,35,28,21,15,16,12
19688,2015/12/31,古亭,NOx,8,6,5.5,5.6,6.1,8.2,15,...,31,30,34,39,39,31,24,17,18,14
19689,2015/12/31,古亭,O3,36,38,38,40,40,37,34,...,30,31,28,27,29,42,45,45,40,43
19690,2015/12/31,古亭,PM10,41,26,31,23,30,27,35,...,115,116,110,108,115,120,121,117,118,102
19691,2015/12/31,古亭,PM2.5,5,2,6,6,7,5,5,...,40,47,62,53,52,56,68,69,66,55
19692,2015/12/31,古亭,RAINFALL,NR,NR,NR,NR,NR,NR,NR,...,NR,NR,NR,NR,NR,NR,NR,NR,NR,NR
19693,2015/12/31,古亭,RH,94,93,93,91,91,92,91,...,69,69,70,70,70,69,71,74,75,72
19694,2015/12/31,古亭,SO2,1.5,1.7,1.3,1.1,1.2,1.6,2.6,...,4.8,5,6,6.7,8.6,8,6.3,3.6,2.7,2.5
19695,2015/12/31,古亭,THC,2,2,1.9,1.9,1.9,1.9,1.9,...,2.2,2.2,2.2,2.2,2.2,2.1,2.1,2.1,2.1,2
19696,2015/12/31,古亭,WD_HR,104,99,103,102,102,100,93,...,89,93,100,101,96,96,98,99,105,107
19697,2015/12/31,古亭,WIND_DIREC,101,88,98,97,91,113,92,...,80,97,104,106,100,100,100,97,109,101
19698,2015/12/31,古亭,WIND_SPEED,2.9,2.3,2.2,2.2,2.3,2.9,2.6,...,3.2,2.9,3.2,3.1,2.3,3.4,3.1,3.4,3.2,3.1
19699,2015/12/31,古亭,WS_HR,2.5,2.2,2.3,2.2,2.3,2.3,2.5,...,2.5,2.8,2.7,2.5,2.4,2.9,3.1,3.4,2.9,3.2

## Indexes introduce

In [3]:
date = pd.Series(sheet1.iloc[:,0].real).unique()
index = pd.Series(['AMB_TEMP','RAINFALL', 'RH', 'WIND_SPEED', 'WIND_DIREC', 'WS_HR', 'WD_HR','PM10','PM2.5'])

# Data Straucture
print("★☆ Data Period :", date[:1],"~", date[-1:])
print()
print("★☆ All indexes : \n",
      index[0],"   : 大氣溫度(℃)\n",
      index[1],"   : 雨量(mm)\n",
      index[2],"         : 相對溼度(%)\n",
      index[3]," : 風速(m/sec)\n",
      index[4]," : 風向(degress)\n",
      index[5],"      : 風速小時值(m/sec)\n",
      index[6],"      : 風向小時值(degress)\n",
      index[7],"       : 懸浮微粒(μg/m3)\n",
      index[8],"      : 細懸浮微粒(μg/m3)\n",
     )

★☆ Data Period : ['2013/01/01'] ~ ['2015/12/31']

★☆ All indexes :
 AMB_TEMP    : 大氣溫度(℃)
 RAINFALL    : 雨量(mm)
 RH          : 相對溼度(%)
 WIND_SPEED  : 風速(m/sec)
 WIND_DIREC  : 風向(degress)
 WS_HR       : 風速小時值(m/sec)
 WD_HR       : 風向小時值(degress)
 PM10        : 懸浮微粒(μg/m3)
 PM2.5       : 細懸浮微粒(μg/m3)

## Data transpose

In [4]:
def DataTranspose(indexInput):
    dd_OK = pd.DataFrame()
    a = sheet1[sheet1['測項']==indexInput]
    a.drop(['測站','測項','日期'], axis=1, inplace=True)
    b = a.T
    col = list(b.columns)
    for c in col:
        d = b[c]
        dd_OK = pd.concat([dd_OK,d])
    dd_OK.columns=[indexInput]
    return dd_OK

AMB_TEMP = DataTranspose('AMB_TEMP')
RAINFALL = DataTranspose('RAINFALL')
RH = DataTranspose('RH')
WIND_SPEED = DataTranspose('WIND_SPEED')
WIND_DIREC = DataTranspose('WIND_DIREC')
WS_HR = DataTranspose('WS_HR')
WD_HR = DataTranspose('WD_HR')
PM10 = DataTranspose('PM10')
PM25=DataTranspose('PM2.5')

stra = pd.concat([AMB_TEMP, RAINFALL, RH, WIND_SPEED, WIND_DIREC, WS_HR, WD_HR, PM10, PM25], axis=1 )
stra["Hour"] = stra.index
stra.index = range(stra.shape[0])

print("★☆ After transpose :")
print("    Rows : ", stra.shape[0], "; Columns : ", stra.shape[1])
print("★☆ First 5 rows↓")
stra.head(5)

C:\Users\Olly\Miniconda3\lib\site-packages\ipykernel\__main__.py:4: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy

★☆ After transpose :
    Rows :  26280 ; Columns :  10
★☆ First 5 rows↓

  AMB_TEMP RAINFALL  RH WIND_SPEED WIND_DIREC WS_HR WD_HR PM10 PM2.5 Hour
0       13       NR  71        2.5         98   2.3    97   53    27   00
1       13       NR  72        2.6         76   2.6    93   54    27   01
2       14       NR  71        2.6         69   2.6    69   62    25   02
3       14       NR  69          2         83   2.1    76   55    27   03
4       14       NR  70        1.8        100   1.9    79   50    28   04

## Chage 'Date' to 'Season' & change 'Hour' to 'DayPeriod'

In [5]:
# Add Date
Date_col=[]
for d in date:
    eachday = [d]*24
    Date_col = Date_col +eachday
stra["Date"] = Date_col

# Add Season
def DateToSeason(row):
    if (row['Date'][5:7] == '03')|(row['Date'][5:7] == '04')|(row['Date'][5:7] == '05'):
        return 'Q1'
    elif (row['Date'][5:7] == '06')|(row['Date'][5:7] == '07')|(row['Date'][5:7] == '08'):
        return 'Q2'
    elif (row['Date'][5:7] == '09')|(row['Date'][5:7] == '10')|(row['Date'][5:7] == '11'):
        return 'Q3'
    elif (row['Date'][5:7] == '12')|(row['Date'][5:7] == '01')|(row['Date'][5:7] == '02'):
        return 'Q4'
    else:
        return np.nan

stra['Season'] = stra.apply(DateToSeason, axis=1) 
del stra['Date']

#pd.Series(stra.iloc[:,9].real).unique()

# Change hour to DayPeriod
def Hour_To_DayPeriod(row):
    if ((row['Hour'] == '00') | (row['Hour'] == '01')| (row['Hour'] == '02')| (row['Hour'] == '03')| (row['Hour'] == '04')| (row['Hour'] == '05')):
        return 'Midnight'
    elif ((row['Hour'] == '06') | (row['Hour'] == '07')| (row['Hour'] == '08')| (row['Hour'] == '09')| (row['Hour'] == 10)| (row['Hour'] == 11)):
        return 'Morning'
    elif ((row['Hour'] == 12) | (row['Hour'] == 13)| (row['Hour'] == 14)| (row['Hour'] == 15)| (row['Hour'] == 16)| (row['Hour'] == 17)):
        return 'Afternoon'
    elif ((row['Hour'] == 18) | (row['Hour'] == 19)| (row['Hour'] == 20)| (row['Hour'] == 21)| (row['Hour'] == 22)| (row['Hour'] == 23)):
        return 'Evening'    
    else:
        return np.nan

stra['DayPeriod'] = stra.apply(Hour_To_DayPeriod, axis=1) 

del stra['Hour']

#pd.crosstab(stra['DayPeriod'],stra['Hour'])
print("★☆ After chage 'Date' to 'Season' & change 'hour' to 'DayPeriod' :")
print("    Rows : ", stra.shape[0], "; Columns : ", stra.shape[1])
print("★☆ First 5 rows↓")
stra.head(5)

★☆ After chage 'Date' to 'Season' & change 'hour' to 'DayPeriod' :
    Rows :  26280 ; Columns :  11
★☆ First 5 rows↓

,AMB_TEMP,RAINFALL,RH,WIND_SPEED,WIND_DIREC,WS_HR,WD_HR,PM10,PM2.5,Season,DayPeriod
0,13,NR,71,2.5,98,2.3,97,53,27,Q4,Midnight
1,13,NR,72,2.6,76,2.6,93,54,27,Q4,Midnight
2,14,NR,71,2.6,69,2.6,69,62,25,Q4,Midnight
3,14,NR,69,2,83,2.1,76,55,27,Q4,Midnight
4,14,NR,70,1.8,100,1.9,79,50,28,Q4,Midnight

## Dealing Missing Values

In [6]:
print("★☆ Dealing Missing Values")
print("    # 表示儀器檢核為無效值\n"
      "    * 表示程式檢核為無效值\n"
      "    x 表示人工檢核為無效值\n"
      "    NR 表示無降雨\n"
      "    空白 表示缺值")
print()
mis=[]
for s in range(0,9):
    ss = list(pd.Series(stra.iloc[:,s].real).unique())
    for sss in ss:
       mis.append(sss)

miss=[]
for el in mis:
        if type(el) == type('XX'):
            miss.append(el)
print("★☆ Total ",len(miss)," types of missing value :\n ", miss)
print()
print("★☆ Replace missing to Nan; replace NR to 0")
DealNR = stra.replace('NR', 0)
rep = DealNR.replace(miss, np.nan)
rep[:5]

★☆ Dealing Missing Values
    # 表示儀器檢核為無效值
    * 表示程式檢核為無效值
    x 表示人工檢核為無效值
    NR 表示無降雨
    空白 表示缺值

★☆ Total  362  types of missing value :
  ['18#', '16#', '25#', '17#', '27#', '21#', '32#', '31#', '28#', '13#', '23#', '22#', '5.4#', '34#', '24#', '12#', '29#', '55#', '0#', '36#', '33#', '11#', 'NR', '0#', '.2#', '0.2#', '2.2#', '0.4#', '1.4#', '1.6#', '80#', '69#', '53#', '77#', '60#', '67#', '66#', '62#', '83#', '100#', '63#', '90#', '25#', '55#', '82#', '88#', '81#', '89#', '61#', '57#', '86#', '11#', '0#', '54#', '32#', '36#', '37#', '98#', '99#', '84#', '73#', '93#', '96#', '65#', '59#', '87#', '79#', '70#', '2.1#', '3.6#', '1.4#', '3.3#', '2.5#', '2.4#', '3#', '0#', '1.9#', '.9#', '4.3#', '3.1#', '0.6#', '0.7#', '1.8#', '4.4#', '2.2#', '3.2#', '2.6#', '1.3#', '1.5#', '88#', '80#', '335#', '64#', '224#', '111#', '79#', '0#', '108#', '14#', '109#', '74#', '240#', '189#', '305#', '96#', '260#', '90#', '66#', '84#', '93#', '89#', '320#', '30#', '312#', '147#', '136#', '2#', '3.3#', '.6#', '2.9#', '.9#', '2.2#', '2.7#', '2.3#', '1#', '1.2#', '.4#', '3.9#', '2.8#', '2.4#', '0.6#', '2.5#', '0.7#', '1.6#', '0.4#', '3.6#', '1.9#', '2.6#', '3.1#', '1.4#', '2.1#', '0#', '1.8#', '3.4#', '1.3#', '0.1#', '0.3#', '0.8#', '0.9#', '0.5#', '77#', '79#', '296#', '70#', '242#', '111#', '75#', '93#', '91#', '45#', '50#', '121#', '48#', '227#', '193#', '305#', '92#', '55#', '25#', '260#', '88#', '90#', '86#', '321#', '69#', '0#', '72#', '26#', '310#', '95#', '318#', '312#', '65#', '0.9#', '0.8#', '81#', '64#', '243#', '294#', '147#', '104#', '169#', '319#', '97#', '138#', '185#', '30#', '116#', '342#', '74#', '67#', '3374#', '6686#', '9999#', '90x', '91x', '92x', '0#', '140x', '3472#', '6797#', '9330#', '6350#', '4008#', '3656#', '3985#', '7318#', '5688#', '8369#', '9298#', '6531#', '4237#', '1784*', '4550#', '7545#', '7767#', '7725#', '4571#', '1297*', '328x', '89x', '276x', '270x', '64x', '38x', '8x', '9x', '15x', '22x', '19x', '16x', '12x', '14x', '18x', '13x', '7x', '20x', '17x', '10x', '5x', '3x', '2x', '21x', '23x', '11x', '29x', '35x', '31x', '27x', '232x', '52x', '59x', '34x', '36x', '33x', '40x', '39x', '25x', '30x', '43x', '37x', '48x', '44x', '50x', '24x', '28x', '46x', '54*', '46*', '43*', '0#', '62*', '51*', '28*', '41*', '47*', '40*', '58*', '48*', '53*', '30*', '24*', '21x', '20x', '4x', '11x', '6x', '5x', '10x', '13x', '9x', '12x', '7x', '14x', '16x', '8x', '15x', '1x', '-5#', '45*', '20*', '33*', '18*', '23*', '19*', '29*', '39*', '42*', '31*', '32*', '25*', '30#', '-3#', '-4#', '628*', '894*', '941*', '912*', '61*', '408*', '395*', '333*', '19#', '10#', '-2#', '12#', '592*', '26#', '575#', '0x', '1#', '17x', '19x', '33x', '11#', '18x', '25x', '22x', '27*', '26x', '32x', '23x', '29x', '27x', '28x', '606*', '21#', '6#', '2#', '608*', '610*', '13#']

★☆ Replace missing to Nan; replace NR to 0

,AMB_TEMP,RAINFALL,RH,WIND_SPEED,WIND_DIREC,WS_HR,WD_HR,PM10,PM2.5,Season,DayPeriod
0,13.0,0.0,71.0,2.5,98.0,2.3,97.0,53.0,27.0,Q4,Midnight
1,13.0,0.0,72.0,2.6,76.0,2.6,93.0,54.0,27.0,Q4,Midnight
2,14.0,0.0,71.0,2.6,69.0,2.6,69.0,62.0,25.0,Q4,Midnight
3,14.0,0.0,69.0,2.0,83.0,2.1,76.0,55.0,27.0,Q4,Midnight
4,14.0,0.0,70.0,1.8,100.0,1.9,79.0,50.0,28.0,Q4,Midnight

## Create Target variable

In [7]:
print("★☆ Create & Mapping Target variable")
a = rep
b = list(a['RAINFALL'])
b.pop(0)
b.append(np.nan)
a['RAINFALL_Next1'] = b

c = list(a['RAINFALL'])
c.pop(0)
c.pop(0)
c.append(np.nan)
c.append(np.nan)
a['RAINFALL_Next2'] = c

print("  'RAINFALL'       : ", len(list(a['RAINFALL'])), "Rows; ",list(a['RAINFALL'])[:5], list(a['RAINFALL'])[-5:])
print("  'RAINFALL_Next1' : ", len(b), "Rows; ", b[:5], b[-5:])
print("  'RAINFALL_Next2' : ", len(c), "Rows; ", c[:5], c[-5:])

def TargetTransform(row):
    if ((row['RAINFALL'] > 0) & (row['RAINFALL_Next1'] > 0) & (row['RAINFALL_Next2'] == 0)) :
        return 1
    elif ((row['RAINFALL'] > 0) & (row['RAINFALL_Next1'] > 0) & (row['RAINFALL_Next2'] > 0)) :
        return 0
    else:
        return np.nan

a['Target'] = a.apply(TargetTransform, axis=1)

★☆ Create & Mapping Target variable
  'RAINFALL'       :  26280 Rows;  [0.0, 0.0, 0.0, 0.0, 0.0] [0.0, 0.0, 0.0, 0.0, 0.0]
  'RAINFALL_Next1' :  26280 Rows;  [0.0, 0.0, 0.0, 0.0, 0.0] [0.0, 0.0, 0.0, 0.0, nan]
  'RAINFALL_Next2' :  26280 Rows;  [0.0, 0.0, 0.0, 0.0, 0.0] [0.0, 0.0, 0.0, nan, nan]

In [8]:
#a.sort_values(['Target_RAINFALL'], ascending=[0])
TT = a[(a['Target']>=0)]
print("★☆ Keep valueable data ('Target'= 0 OR 1)")
print("    Rows : ", TT.shape[0], "; Columns : ", TT.shape[1])
print()
print("★☆ 'Nan'% in each variable :")
print(TT.isnull().sum()/int(TT.shape[0])*100)
print()
print("★☆ After Clean 'Nan' :")
for c in index:
      TT = TT[np.isfinite(TT[c])]
print("    Rows : ", TT.shape[0], "; Columns : ", TT.shape[1])
print()
print("★☆ First 5 rows↓")
TT[:5]

★☆ Keep valueable data ('Target'= 0 OR 1)
    Rows :  2163 ; Columns :  14

★☆ 'Nan'% in each variable :
AMB_TEMP          0.046232
RAINFALL          0.000000
RH                0.462321
WIND_SPEED        0.000000
WIND_DIREC        0.000000
WS_HR             0.000000
WD_HR             0.046232
PM10              0.647249
PM2.5             2.820157
Season            0.000000
DayPeriod         0.000000
RAINFALL_Next1    0.000000
RAINFALL_Next2    0.000000
Target            0.000000
dtype: float64

★☆ After Clean 'Nan' :
    Rows :  2085 ; Columns :  14

★☆ First 5 rows↓

,AMB_TEMP,RAINFALL,RH,WIND_SPEED,WIND_DIREC,WS_HR,WD_HR,PM10,PM2.5,Season,DayPeriod,RAINFALL_Next1,RAINFALL_Next2,Target
9,13.0,0.4,85.0,1.9,88.0,2.0,74.0,52.0,35.0,Q4,Morning,0.2,1.4,0.0
10,13.0,0.2,90.0,1.9,87.0,1.8,78.0,46.0,37.0,Q4,Morning,1.4,0.8,0.0
11,13.0,1.4,90.0,2.8,84.0,2.4,86.0,40.0,34.0,Q4,Morning,0.8,0.4,0.0
12,13.0,0.8,91.0,2.6,106.0,2.1,89.0,42.0,19.0,Q4,Afternoon,0.4,0.4,0.0
13,13.0,0.4,91.0,2.5,87.0,2.2,88.0,40.0,23.0,Q4,Afternoon,0.4,0.8,0.0

## Add varibles (WS_Change, WD_Change, PM10_25)

In [9]:
del TT['RAINFALL_Next1']
del TT['RAINFALL_Next2']
TT['WS_Change'] = TT['WIND_SPEED'] - TT['WS_HR']
del TT['WIND_SPEED']
TT['WD_Change'] = abs(TT['WIND_DIREC'] - TT['WD_HR'])
del TT['WIND_DIREC']
TT['PM10_25'] = TT['PM10'] - TT['PM2.5']
TT['PM25']=TT['PM2.5']
del TT['PM10']
del TT['PM2.5']
TT.head()

,AMB_TEMP,RAINFALL,RH,WS_HR,WD_HR,Season,DayPeriod,Target,WS_Change,WD_Change,PM10_25,PM25
9,13.0,0.4,85.0,2.0,74.0,Q4,Morning,0.0,-0.1,14.0,17.0,35.0
10,13.0,0.2,90.0,1.8,78.0,Q4,Morning,0.0,0.1,9.0,9.0,37.0
11,13.0,1.4,90.0,2.4,86.0,Q4,Morning,0.0,0.4,2.0,6.0,34.0
12,13.0,0.8,91.0,2.1,89.0,Q4,Afternoon,0.0,0.5,17.0,23.0,19.0
13,13.0,0.4,91.0,2.2,88.0,Q4,Afternoon,0.0,0.3,1.0,17.0,23.0

## Wind direction transform (WD_HR)

<div class="clearfix" style="padding: 10px; padding-left: 0px">
<img src="http://4.bp.blogspot.com/-XFAo2HP4bDg/Vb3mykmb3oI/AAAAAAAAF_U/yOj2GKXZOY4/s1600/%25E6%2596%25B9%25E4%25BD%258D.jpg" width="450px" style="display: inline-block; margin-top: 5px;">
</div>

In [10]:
def WD_HR_To_WD_HR_gp(row):
    if (row['WD_HR'] >0) & (row['WD_HR'] <=45):
        return 'EN'
    elif (row['WD_HR'] >45) & (row['WD_HR'] <=90):
        return 'EN'
    elif (row['WD_HR'] >90) & (row['WD_HR'] <=135):
        return 'ESE'
    elif (row['WD_HR'] >135) & (row['WD_HR'] <=180):
        return 'SSE'
    elif (row['WD_HR'] >180) & (row['WD_HR'] <=225):
        return 'SSW'
    elif (row['WD_HR'] >225) & (row['WD_HR'] <=270):
        return 'WSW'
    elif (row['WD_HR'] >270) & (row['WD_HR'] <=315):
        return 'WN'
    elif (row['WD_HR'] >315):
        return 'WN'
    else:
        return np.nan

TT['WD_HR_gp'] = TT.apply(WD_HR_To_WD_HR_gp, axis=1) 
del TT['WD_HR']

print("★☆ Final Data snapshot")
TT.head()

★☆ Final Data snapshot

,AMB_TEMP,RAINFALL,RH,WS_HR,Season,DayPeriod,Target,WS_Change,WD_Change,PM10_25,PM25,WD_HR_gp
9,13.0,0.4,85.0,2.0,Q4,Morning,0.0,-0.1,14.0,17.0,35.0,EN
10,13.0,0.2,90.0,1.8,Q4,Morning,0.0,0.1,9.0,9.0,37.0,EN
11,13.0,1.4,90.0,2.4,Q4,Morning,0.0,0.4,2.0,6.0,34.0,EN
12,13.0,0.8,91.0,2.1,Q4,Afternoon,0.0,0.5,17.0,23.0,19.0,EN
13,13.0,0.4,91.0,2.2,Q4,Afternoon,0.0,0.3,1.0,17.0,23.0,EN

##  Plot categorical varibles distribution

In [11]:
print("★☆ Plot Target with pie chart")
NR =TT[(TT['Target']==1)]
R = TT[(TT['Target']==0)]

series = pd.Series([NR.shape[0],R.shape[0]], index=['No Rain','Rain'],name='')
series.plot.pie(figsize=(7, 7), autopct='%.2f', fontsize=20)
pl.title("Target %", fontsize = 25)
pl.show()

print("★☆ Plot Season with pie chart")
Q1 =TT[(TT['Season']=='Q1')]
Q2 = TT[(TT['Season']=='Q2')]
Q3 =TT[(TT['Season']=='Q3')]
Q4 = TT[(TT['Season']=='Q4')]

series = pd.Series([Q1.shape[0],Q2.shape[0],Q3.shape[0],Q4.shape[0]], index=['Spring', 'Summer','Autumn','Winter'], name='')
series.plot.pie(figsize=(7, 7), autopct='%.2f', fontsize=20)
pl.title("Season %", fontsize = 25)
pl.show()

print("★☆ Plot DayPeriod with pie chart")
P1 =TT[(TT['DayPeriod']=='Midnight')]
P2 = TT[(TT['DayPeriod']=='Morning')]
P3 =TT[(TT['DayPeriod']=='Afternoon')]
P4 = TT[(TT['DayPeriod']=='Evening')]

series = pd.Series([P1.shape[0],P2.shape[0],P3.shape[0],P4.shape[0]], index=['Midnight', 'Morning','Afternoon','Evening'], name='')
series.plot.pie(figsize=(7, 7), autopct='%.2f', fontsize=20)
pl.title("DayPeriod %", fontsize = 25)
pl.show()

print("★☆ Plot WIND_DIREC_gp with pie chart")
Gp =[]
for i in range(0,6):
    G =TT.groupby(['WD_HR_gp']).size()[i]
    Gp.append(G)
#TT.groupby(['WD_HR_gp']).size()

series = pd.Series(Gp, index=['EN','ESE','SSE','SSW','WN','WSW'], name='')
series.plot.pie(figsize=(7, 7), autopct='%.2f', fontsize=20)
pl.title("Wind Direction %", fontsize = 25)

pl.show()
TT.head()

★☆ Plot Target with pie chart
★☆ Plot Season with pie chart
★☆ Plot DayPeriod with pie chart
★☆ Plot WIND_DIREC_gp with pie chart

,AMB_TEMP,RAINFALL,RH,WS_HR,Season,DayPeriod,Target,WS_Change,WD_Change,PM10_25,PM25,WD_HR_gp
9,13.0,0.4,85.0,2.0,Q4,Morning,0.0,-0.1,14.0,17.0,35.0,EN
10,13.0,0.2,90.0,1.8,Q4,Morning,0.0,0.1,9.0,9.0,37.0,EN
11,13.0,1.4,90.0,2.4,Q4,Morning,0.0,0.4,2.0,6.0,34.0,EN
12,13.0,0.8,91.0,2.1,Q4,Afternoon,0.0,0.5,17.0,23.0,19.0,EN
13,13.0,0.4,91.0,2.2,Q4,Afternoon,0.0,0.3,1.0,17.0,23.0,EN

## Plot numeric variables distribution

In [ ]:
print("★☆ Plot Numeric Variable Distribution")
fig = pl.figure(figsize=(16.7, 8))
new_index = ['AMB_TEMP','RAINFALL','RH','WS_HR','PM10_25','PM25','Hour','Season','Target','WS_Change','WD_Change','WD_HR_gp']
num_index = ['AMB_TEMP','RAINFALL','RH','WS_HR','PM10_25','PM25','WS_Change','WD_Change']
cat_index = ['Hour','Season','Target','WD_HR_gp']
n=331
for i in num_index:
    h = sorted(list(TT[i]))
    fit = stats.norm.pdf(h, np.mean(h), np.std(h))  #this is a fitting indeed
    sub = fig.add_subplot(n)
    sub.hist(h,normed=True)
    sub.plot(h,fit,'-o')
    sub.set_title(i+' Distribution', fontsize=16)
    n = n+1
    
pl.tight_layout()
pl.show()

grouped = TT.groupby('Target')
grouped.agg([np.mean,np.std])

★☆ Plot Numeric Variable Distribution

## Detect rows meet outlier criteria

In [32]:
deO_TT = TT
deO_TT = deO_TT[((deO_TT.AMB_TEMP - deO_TT.AMB_TEMP.mean()) / deO_TT.AMB_TEMP.std()).abs() < 3]
deO_TT = deO_TT[((deO_TT.RAINFALL - deO_TT.RAINFALL.mean()) / deO_TT.RAINFALL.std()).abs() < 3]
deO_TT = deO_TT[((deO_TT.RH - deO_TT.RH.mean()) / deO_TT.RH.std()).abs() < 3]
deO_TT = deO_TT[((deO_TT.WS_HR - deO_TT.WS_HR.mean()) / deO_TT.WS_HR.std()).abs() < 3]
deO_TT = deO_TT[((deO_TT.PM10_25 - deO_TT.PM10_25.mean()) / deO_TT.PM10_25.std()).abs() < 3]
deO_TT = deO_TT[((deO_TT.PM25 - deO_TT.PM25.mean()) / deO_TT.PM25.std()).abs() < 3]
deO_TT = deO_TT[((deO_TT.WS_Change - deO_TT.WS_Change.mean()) / deO_TT.WS_Change.std()).abs() < 3]
deO_TT = deO_TT[((deO_TT.WD_Change - deO_TT.WD_Change.mean()) / deO_TT.WD_Change.std()).abs() < 3]
print("There are ", TT.shape[0]-deO_TT.shape[0], "(%.3f %%) rows meet the critirias of outlier. " %((TT.shape[0]-deO_TT.shape[0])/TT.shape[0]*100)) 

grouped = deO_TT.groupby('Target')
grouped.agg([np.mean,np.std])

There are  211 (10.120 %) rows meet the critirias of outlier.

         AMB_TEMP            RAINFALL                   RH            \
             mean       std      mean       std       mean       std
Target
0.0     19.654164  5.325758  2.127222  2.854741  94.216935  5.530204
1.0     21.060449  5.066531  1.702921  2.625192  93.047191  6.103833

           WS_HR           WS_Change            WD_Change             \
            mean       std      mean       std       mean        std
Target
0.0     1.724563  0.882481  0.299090  0.457209  15.767110  20.086841
1.0     1.617303  0.845759  0.286966  0.471351  16.255955  19.552704

          PM10_25                 PM25
             mean       std       mean        std
Target
0.0     17.370189  9.313824  15.532540  10.726996
1.0     18.923596  9.564316  16.395506  11.323697

## Model split (90%, 10%)

In [33]:
features = ['AMB_TEMP','RAINFALL','RH','WS_HR','PM10_25','PM25','Season','DayPeriod','WS_Change','WD_Change','WD_HR_gp']
TT.index = range(len(TT))

X = TT[features]
y = TT['Target']

# A random permutation, to split the data randomly
np.random.seed(1234)
indices = np.random.permutation(len(TT))

# Split train and test data
idx1, idx2 = train_test_split(indices, test_size=0.1, random_state=0)
Train_data = TT.iloc[idx1]
Test_data = TT.iloc[idx2]
print("★☆ Train_data : rows : ", Train_data.shape[0], "; columns : ", Train_data.shape[1])
print(Train_data.groupby(['Target']).size())
print()
print("★☆ Test_data : rows : ", Test_data.shape[0], "; columns : ", Test_data.shape[1])
print(Test_data.groupby(['Target']).size())

★☆ Train_data : rows :  1876 ; columns :  12
Target
0.0    1439
1.0     437
dtype: int64

★☆ Test_data : rows :  209 ; columns :  12
Target
0.0    155
1.0     54
dtype: int64

In [34]:
y=0
X=0
def LogisticReg_Xy(Train_data, Test_data):
    yt, Xt = dmatrices('Target ~ AMB_TEMP + RAINFALL + RH + WS_HR + PM10_25 + PM25 + WS_Change + WD_Change + C(Season) + C(DayPeriod) + C(WD_HR_gp)',
                  Train_data, return_type="dataframe")

    Xt = Xt.rename(columns = {'C(Season)[T.Q2]':'Season_Q2',
                            'C(Season)[T.Q3]':'Season_Q3',
                            'C(Season)[T.Q4]':'Season_Q4',
                            'C(DayPeriod)[T.Evening]':'DayP_Evening',
                            'C(DayPeriod)[T.Midnight]':'DayP_Midnight',
                            'C(DayPeriod)[T.Morning]':'DayP_Morning',
                            'C(WD_HR_gp)[T.ESE]':'WDHRgp_ESE',
                            'C(WD_HR_gp)[T.SSE]':'WDHRgp_SSE',
                            'C(WD_HR_gp)[T.SSW]':'WDHRgp_SSW',
                            'C(WD_HR_gp)[T.WN]':'WDHRgp_WN',
                            'C(WD_HR_gp)[T.WSW]':'WDHRgp_WSW'})

    yt = np.ravel(yt)
    
    yw, Xw = dmatrices('Target ~ AMB_TEMP + RAINFALL + RH + WS_HR + PM10_25 + PM25 + WS_Change + WD_Change + C(Season) + C(DayPeriod) + C(WD_HR_gp)',
                  Test_data, return_type="dataframe")

    Xw = Xw.rename(columns = {'C(Season)[T.Q2]':'Season_Q2',
                            'C(Season)[T.Q3]':'Season_Q3',
                            'C(Season)[T.Q4]':'Season_Q4',
                            'C(DayPeriod)[T.Evening]':'DayP_Evening',
                            'C(DayPeriod)[T.Midnight]':'DayP_Midnight',
                            'C(DayPeriod)[T.Morning]':'DayP_Morning',
                            'C(WD_HR_gp)[T.ESE]':'WDHRgp_ESE',
                            'C(WD_HR_gp)[T.SSE]':'WDHRgp_SSE',
                            'C(WD_HR_gp)[T.SSW]':'WDHRgp_SSW',
                            'C(WD_HR_gp)[T.WN]':'WDHRgp_WN',
                            'C(WD_HR_gp)[T.WSW]':'WDHRgp_WSW'})

    yw = np.ravel(yw)
    return yt, Xt, yw, Xw

# Trainin/Testing data X y create
yt, Xt, yw, Xw = LogisticReg_Xy(Train_data, Test_data)
Xt[:5]

,Intercept,Season_Q2,Season_Q3,Season_Q4,DayP_Evening,DayP_Midnight,DayP_Morning,WDHRgp_ESE,WDHRgp_SSE,WDHRgp_SSW,WDHRgp_WN,WDHRgp_WSW,AMB_TEMP,RAINFALL,RH,WS_HR,PM10_25,PM25,WS_Change,WD_Change
282,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,21.0,0.2,92.0,1.2,5.0,39.0,0.2,3.0
2077,1.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,17.0,0.4,93.0,1.7,4.0,5.0,1.3,16.0
1239,1.0,1.0,0.0,0.0,1.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,26.0,12.0,99.0,1.0,13.0,9.0,0.0,12.0
2030,1.0,0.0,1.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,22.0,2.4,95.0,1.8,13.0,1.0,0.1,6.0
1590,1.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,13.0,1.2,99.0,2.2,12.0,3.0,0.8,3.0

In [35]:
print("★☆ Training data : ")
print("     Xt  rows : ", Xt.shape[0], "; columns : ", Xt.shape[1])
print("     yt  number : ", len(yt))
print()
print("★☆ Testing data : ")
print("     Xw  rows : ", Xw.shape[0], "; columns : ", Xw.shape[1])
print("     yw  number : ", len(yw))

★☆ Training data :
     Xt  rows :  1876 ; columns :  20
     yt  number :  1876

★☆ Testing data :
     Xw  rows :  209 ; columns :  20
     yw  number :  209

## Performance section check function

In [36]:
def Section10Performance(prob_pos, df):
    Sec10 = []
    for i in range(0, len(prob_pos)):
        if prob_pos[i] >= 0.95:
            Sec10.append(['A95_100'])
        elif prob_pos[i] >= 0.90 and prob_pos[i] < 0.95:
            Sec10.append(['B90_94'])
        elif prob_pos[i] >= 0.85 and prob_pos[i] < 0.90:
            Sec10.append(['C85_89'])
        elif prob_pos[i] >= 0.80 and prob_pos[i] < 0.85:
            Sec10.append(['D80_84'])
        elif prob_pos[i] >= 0.75 and prob_pos[i] < 0.80:
            Sec10.append(['E75_79'])
        elif prob_pos[i] >= 0.70 and prob_pos[i] < 0.75:
            Sec10.append(['F70_74'])
        elif prob_pos[i] >= 0.65 and prob_pos[i] < 0.70:
            Sec10.append(['G65_69'])
        elif prob_pos[i] >= 0.60 and prob_pos[i] < 0.65:
            Sec10.append(['H60_64'])
        elif prob_pos[i] >= 0.55 and prob_pos[i] < 0.60:
            Sec10.append(['I55_59'])
        elif prob_pos[i] >= 0.50 and prob_pos[i] < 0.55:
            Sec10.append(['J50_54'])
        elif prob_pos[i] >= 0.45 and prob_pos[i] < 0.50:
            Sec10.append(['K45_49'])
        elif prob_pos[i] >= 0.40 and prob_pos[i] < 0.45:
            Sec10.append(['L40_44'])
        elif prob_pos[i] >= 0.35 and prob_pos[i] < 0.40:
            Sec10.append(['M35_39'])
        elif prob_pos[i] >= 0.30 and prob_pos[i] < 0.35:
            Sec10.append(['N30_34'])
        elif prob_pos[i] >= 0.25 and prob_pos[i] < 0.30:
            Sec10.append(['O25_29'])
        elif prob_pos[i] >= 0.20 and prob_pos[i] < 0.25:
            Sec10.append(['P20_24'])
        elif prob_pos[i] >= 0.15 and prob_pos[i] < 0.20:
            Sec10.append(['Q15_19'])
        elif prob_pos[i] >= 0.10 and prob_pos[i] < 0.15:
            Sec10.append(['R10_14'])
        elif prob_pos[i] >= 0.05 and prob_pos[i] < 0.10:
            Sec10.append(['S05_09'])
        elif prob_pos[i] < 0.05:
            Sec10.append(['T00_05'])
        else:
            Sec10.append(['UU'])

    Sec_df = pd.DataFrame(Sec10)
    return pd.crosstab(Sec_df[0], df)

# Logistic regression
## Training data performance

In [37]:
model = LogisticRegression()
model = model.fit(Xt, yt)
print("★☆ Training model accuracy: %.2f " % model.score(Xt, yt))

# evaluate the model using 10-fold cross-validation
scores = cross_val_score(LogisticRegression(), Xt, yt, scoring='accuracy', cv=10)
print ("★☆ 10-fold cross-validation accuracies: \n", scores)

★☆ Training model accuracy: 0.77
★☆ 10-fold cross-validation accuracies:
 [ 0.7606383   0.7712766   0.76595745  0.76595745  0.7606383   0.7712766
  0.7712766   0.77540107  0.78074866  0.7688172 ]

## Testing data performance

In [38]:
predicted = model.predict(Xw)
print("★☆ Test model accuracy: %.2f " % metrics.roc_auc_score(yw, predicted))
prob = model.predict_proba(Xw)[:, 1]
Section10Performance(prob, yw)

★☆ Test model accuracy: 0.50

col_0   0.0  1.0
0
L40_44    2    2
M35_39    5    3
N30_34   16   12
O25_29   24   11
P20_24   30   13
Q15_19   42    9
R10_14   28    4
S05_09    5    0
T00_05    3    0

# Decision tree

In [39]:
from sklearn.cross_validation import KFold
from sklearn import tree

## Training data performance

In [40]:
dt = tree.DecisionTreeClassifier(max_depth=8, random_state=0)
dt = dt.fit(Xt, yt)
print("★☆ Training model accuracy: %.2f " % dt.score(Xt, yt))
print()
# evaluate the model using 10-fold cross-validation
scores = cross_val_score(tree.DecisionTreeClassifier(max_depth=8,random_state=0), Xt, yt, scoring='accuracy', cv=10)
print ("★☆ 10-fold cross-validation accuracies: \n", scores)

★☆ Training model accuracy: 0.82

★☆ 10-fold cross-validation accuracies:
 [ 0.7287234   0.7606383   0.75531915  0.71276596  0.74468085  0.71276596
  0.70744681  0.68983957  0.76470588  0.69892473]

## Testing data performance

In [41]:
predict = dt.predict(Xw)
print("★☆ Test model accuracy: %.2f " % metrics.roc_auc_score(yw, predict))
print()
prob = dt.predict_proba(Xw)[:, 1]
Section10Performance(prob, yw)

★☆ Test model accuracy: 0.54

col_0    0.0  1.0
0
A95_100    4    3
E75_79     1    0
H60_64     3    4
K45_49     4    3
L40_44     7    2
M35_39    12    7
N30_34    20    4
O25_29     1    1
P20_24     5    6
Q15_19    32    8
R10_14    26    7
S05_09     2    0
T00_05    38    9

# ☼  ☀  ☁  ★☆☼  ☀  ☁  ★☆☼  ☀  ☁  ★☆☼  ☀  ☁  ★☆☼  ☀  ☁  ★☆☼  ☀  ☁  ★☆
# Discuss
## 1. Varibles distibution
## 2. Model comparison
## 3. Summray
<div class="clearfix" style="padding: 10px; padding-left: 0px">
<img src="http://zululandobserver.co.za/wp-content/uploads/sites/56/2015/12/rainy_day_6472504241.jpg" width="600px" style="display: inline-block; margin-top: 5px;">
</div>